name: Auto release on merge

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - ".tflint.hcl"
      - "**/*.md"
      - "renovate.json"

jobs:
  auto-release:
    uses: dfds/shared-workflows/.github/workflows/automation-auto-release.yml@2.0.2
